version: "2.4"

services:
    phpengine:
        container_name: phpengine
        image: thepirateclub/php53-apache
        ports: 
            - 80:80
        volumes: 
            - ./src:/var/www
        networks: 
            - db
            - webapp
    mysql:
        image: mysql:5.6
        container_name: mysqldb
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks: 
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment: 
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=123456
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        restart: always
        volumes:
            - /sessions
        networks: 
            - db

networks: 
    db:
        driver: bridge
    webapp:
        driver: bridge